// https://newsapi.org/v2/top-headlines?sources=google-news&apiKey=b125b5ac47f04bde89c83a496ba13962
import 'dart:convert';
import 'dart:math';

import 'package:http/http.dart';

class FetchNews {
  static List sourcesId = [
    "abc-news",
    "abc-news-au",
    "aftenposten",
    "al-jazeera-english",
    "ansa",
    "argaam",
    "ars-technica",
    "ary-news",
    "associated-press",
    "australian-financial-review",
    "axios",
    "bbc-news",
    "bbc-sport",
    "bild",
    "blasting-news-br",
    "bleacher-report",
    "bloomberg",
    "breitbart-news",
    "business-insider",
    "buzzfeed",
    "cbc-news",
    "cbs-news",
    "cnn",
    "cnn-es",
    "crypto-coins-news",
    "der-tagesspiegel",
    "die-zeit",
    "el-mundo",
    "engadget",
    "entertainment-weekly",
    "espn",
    "espn-cric-info",
    "financial-post",
    "focus",
    "football-italia",
    "fortune",
    "four-four-two",
    "fox-news",
    "fox-sports",
    "globo",
    "google-news",
    "google-news-ar",
    "google-news-au",
    "google-news-br",
    "google-news-ca",
    "google-news-fr",
    "google-news-in",
    "google-news-is",
    "google-news-it",
    "google-news-ru",
    "google-news-sa",
    "google-news-uk",
    "goteborgs-posten",
    "gruenderszene",
    "hacker-news",
    "handelsblatt",
    "ign",
    "il-sole-24-ore",
    "independent",
    "infobae",
    "info-money",
    "la-gaceta",
    "la-nacion",
    "la-repubblica",
    "le-monde",
    "lenta",
    "lequipe",
    "les-echos",
    "liberation",
    "marca",
    "mashable",
    "medical-news-today",
    "msnbc",
    "mtv-news",
    "mtv-news-uk",
    "national-geographic",
    "national-review",
    "nbc-news",
    "news24",
    "new-scientist",
    "news-com-au",
    "newsweek",
    "new-york-magazine",
    "next-big-future",
    "nfl-news",
    "nhl-news",
    "nrk",
    "politico",
    "polygon",
    "rbc",
    "recode",
    "reddit-r-all",
    "rt",
    "rte",
    "rtl-nieuws",
    "sabq",
    "spiegel-online",
    "svenska-dagbladet",
    "t3n",
    "talksport",
    "techcrunch",
    "techcrunch-cn",
    "techradar",
    "the-american-conservative",
    "the-globe-and-mail",
    "the-hill",
    "the-hindu",
    "the-huffington-post",
    "the-irish-times",
    "the-jerusalem-post",
    "the-lad-bible",
    "the-next-web",
    "the-sport-bible",
    "the-times-of-india",
    "the-verge",
    "the-wall-street-journal",
    "the-washington-post",
    "the-washington-times",
    "time",
    "usa-today",
    "vice-news",
    "wired",
    "wired-de",
    "wirtschafts-woche",
    "xinhua-net",
    "ynet",
  ];
  static fetchNews() async {
    final _random = new Random();
    var SourceID = sourcesId[_random.nextInt(sourcesId.length)];
    print("This is Source ID $SourceID");
    Response response = await get(
      Uri.parse(
        "https://newsapi.org/v2/top-headlines?sources=$SourceID&apiKey=b125b5ac47f04bde89c83a496ba13962",
      ),
    );

    Map body_data = jsonDecode(response.body);
    List articles = body_data["articles"];

    print("this is Article $articles");

    final _newArticle = new Random();
    var myArticle = articles[_newArticle.nextInt(articles.length)];

    print("myArticle is $myArticle");
  }
}
